### ISSUE TITLE
百分比转页码

### ISSUE THREAD

**Issue by TonyJason** [newbiechen1024/NovelReader#1]
运行了一下，效果很不错。但是好像很多功能没实现，比如字体大小。切换了翻页动画下次进去还是默认的效果。时间和电量在我手机上不会变。还有就是那个百分比可以搞成页码方式吗，类似这样1/20  每一章这样显示比百分比直观很多。

**Comment by newbiechen1024** [comment]
多谢意见。这个项目只是完成的主要部分，是存在很多的BUG还有未实现的功能，正在修复中。关于字体大小还有页码的功能之后会加上去。手机和电量的问题我自己用的时候没有问题，我没有对机型进行适配，可能你的机型无法使用，方便的话请问下你的机型是什么，我修复一下。

**Comment by TonyJason** [comment]
可以加你的联系方式吗，有些RXJAVA的问题想问你

**Comment by newbiechen1024** [comment]
没问题，那我QQ吧，541567170。
