### ISSUE TITLE
上下滚动模式回滚会出现内容重复

### ISSUE THREAD

**Issue by romantic100** [newbiechen1024/NovelReader#12]

**Comment by newbiechen1024** [comment]
好的，正在修复。。。

**Comment by newbiechen1024** [comment]
问题解决，并更新了。

如果想了解问题产生的原因的话，是这样的：这是代码的逻辑问题。当进入到阅读器的时候，代码首先会加载第一个页面。当我们用手指滑动加载下一页，这时整个屏幕就有两个页面存在了，命名为第一页和第二页，代码就将显示的第二页作为 curPage,也就是当前页。此时再向上滑动，滑动到第二页被隐藏，第一页的上一页被加载。但是由于 curPage 其实是原先的第二页，所以此时获取到的第一页的上一页是第二页的上一页，就是第一页，也就是第一页的上一页加载的内容，还是第一页的内容，所以就导致重复了。。。(可能用图表示更好 /(ㄒoㄒ)/~~)

**Comment by TonyJason** [comment]
@newbiechen1024 手指只能移动一小段距离的 bug。这是什么原因？没看懂

**Comment by newbiechen1024** [comment]
只能移动一小段距离，是我在 ScrollAnimation 中多加了最小滑动距离判断造成的，删掉就好了 。。。
