### ISSUE TITLE
感谢

### ISSUE THREAD

**Issue by ainiyiwan** [newbiechen1024/NovelReader#2]
这个项目还在维护吗？

**Comment by newbiechen1024** [comment]
项目还在维护的，只是最近需要忙别的事情，没有时间维护项目。等忙完了会继续做的。哈哈，很高兴你觉得这个项目还可以。

**Comment by le9527** [comment]
博主，不知道你发现没，仿真和覆盖翻页向上一页翻页时候，有一个地方判断错误了，导致向前翻页出问题，在你的HorzonPageAnim.java里面的onTouchEvent（MotionEvent event）的MotionEvent.ACTION_UP:
事件里面，在判断是否取消翻页的！isNext事件的if (x - mMoveY < 0) 应该改为if (x - mMoveX < 0) 。感谢无私分享！！！

**Comment by le9527** [comment]
博主，向前翻页的时候有个地方判断的不好，导致向前翻页不太灵敏，我按着如风那个对比了一下，给你贴下修改的地方（在HorizonPageAnim中）：
 if (isMove) {
                    //判断是否是准备移动的状态(将要移动但是还没有移动)
                    isMove = true;
                    if (mMoveX == 0 && mMoveY == 0) {
                        //判断翻得是上一页还是下一页
                        if (x - mStartX > 0) {
                            isNext = false;
                        } else {
                            isNext = true;
                        }
                        isCancel = false;
                        if (isNext) {
                            Boolean isNext = mListener.hasNext();
                            setDirection(Direction.NEXT);
                            if (!isNext) {
                                noNext = true;
                                return true;
                            }
                        } else {
                            Boolean isPre = mListener.hasPrev();
                            setDirection(Direction.PRE);

                            if (!isPre) {
                                noNext = true;
                                return true;
                            }
                        }
                    } 
，希望能帮到后来下载的朋友。感谢博主无私奉献精神！！！

**Comment by newbiechen1024** [comment]
谢谢指正，我会尽快修复这个问题。希望你能够创建个issue，这样好让更多朋友看到。项目还有存在很多问题，请继续赐教，谢谢～。
