### ISSUE TITLE
OOM

### ISSUE THREAD

**Issue by SnowDragon2015** [newbiechen1024/NovelReader#20]
楼主已经指出了，这些位置，确实容易OOM
![image](https://user-images.githubusercontent.com/12468468/34088490-a07db98a-e3e4-11e7-9bce-04ef93914892.png)

![image](https://user-images.githubusercontent.com/12468468/34088451-6a687966-e3e4-11e7-85e9-18fbca3a3292.png)
，好久没有更新了，不知楼主是否已找到好的解决方式

**Comment by newbiechen1024** [comment]
很抱歉，由于校招 + 实习换城市，没有时间更新。。最近准备开始修复，谢谢提问
