### ISSUE TITLE
网络odf 是必须先下载在本地吗?

### ISSUE THREAD

**Issue by 15520000820** [newbiechen1024/NovelReader#21]
请问mBookId只能是本地地址吗?如果PDF是一个网络URL该如何处理??

**Comment by newbiechen1024** [comment]
抱歉，暂时不支持 pdf。id 是用来确认书籍的唯一值的，因为本地地址是唯一的我就直接用了，不过我觉得将本地路径转换成 hash 值最为 id 是更好的办法。并不是指的是 url 。
