### ISSUE TITLE
发现一个bug

### ISSUE THREAD

**Issue by HoterCyc** [newbiechen1024/NovelReader#25]
public CollBookBean createCollBookBean(){
        CollBookBean bean = new CollBookBean();
        bean.set_id(get_id());
        bean.setTitle(getTitle());
        bean.setAuthor(bean.getAuthor());//这里应该是 bean.setAuthor(getAuthor());
        bean.setShortIntro(getLongIntro());
        bean.setCover(getCover());
        bean.setHasCp(isHasCp());
        bean.setLatelyFollower(getLatelyFollower());
        bean.setRetentionRatio(Double.parseDouble(getRetentionRatio()));
        bean.setUpdated(getUpdated());
        bean.setChaptersCount(getChaptersCount());
        bean.setLastChapter(getLastChapter());
        return bean;
    }

**Comment by newbiechen1024** [comment]
谢谢，反馈
