### ISSUE TITLE
添加喜欢的小说按钮，前面的图标看不清--白色和白背景不好！~

### ISSUE THREAD

**Issue by HoterCyc** [newbiechen1024/NovelReader#27]
header_disc_review_detail.xml 文件
<TextView
		android:layout_width="match_parent"
		android:layout_height="wrap_content"
		android:drawableLeft="@drawable/ic_book_list_add"//改成ic_book_shelf_add后看得清楚些
		android:drawablePadding="15dp"
		android:gravity="center_vertical"
		android:padding="20dp"
		android:text="添加你喜欢的小说"
		android:textColor="@color/nb.text.default"/>
</LinearLayout>

**Comment by newbiechen1024** [comment]
好的，我改改。
