### ISSUE TITLE
打开无论本地还是在线书籍时强制关闭

### ISSUE THREAD

**Issue by a442509097** [newbiechen1024/NovelReader#5]
public boolean isRunning(){
        return mPageAnim.isRunning();
    }
显示空对象.
另外想问一下楼主, 只是想搞一个简单的text阅读器, 限制每次读取的字节, 当scrollView滑动到底部时再添加上一些内容, 逻辑上没有问题, 但每次添加时textView.append都会造成ui线程的卡顿, 有没有办法解决? 难道只能用canvas.drawText的方式?

**Comment by TonyJason** [comment]
你是想实现上下翻页吗，看你都用了TextView，我觉得你可以使用listview来实现了。每个item里面是TextView，效果比scrollview好，我也试过用scrollview，各种问题。群主这个上下翻页卡顿太明显了，不过思路很不错。

**Comment by newbiechen1024** [comment]
额，这个问题我以为上次修复好了。。。我之后更新个版本上去。原因是我是在PageLoader.onSizeChange()中初始化PageAnim的，但是在ReadActivity注册的Broadcast的回调速度比onSizeChange()方法快。你暂时改成这样子试一试
```java
    // 接收电池信息和时间更新的广播
    private BroadcastReceiver mReceiver = new BroadcastReceiver(){
        @Override
        public void onReceive(Context context, Intent intent) {
            if (intent.getAction().equals(Intent.ACTION_BATTERY_CHANGED)) {
                int level = intent.getIntExtra("level", 0);
                mPvPage.post(
                        ()-> mPageLoader.updateBattery(level)
                );
            }
            //监听分钟的变化
            else if (intent.getAction().equals(Intent.ACTION_TIME_TICK)){
                mPvPage.post(
                        ()-> mPageLoader.updateTime()
                );
            }
        }
    };
```

**Comment by cc976655** [comment]
我的手机每次在阅读界面都很难点击到中间的那个区域唤起菜单。

**Comment by newbiechen1024** [comment]
我没有看过TextView.append()的源码，不太理解卡顿的原因。你可以用测试工具测试一下哪个方法造成的耗时。如果你想要用ScrollView的话，我只能说优化的地方，就是对下一页显示的数据先从文件中读取到内存中进行缓存。TextView显示内容的控件是StaticLayout，你可以去了解一下。我之前使用过，它的显示速度要比使用canvas.drawText()要快很多，但是他的问题也很多，主要的问题是文本不对称的问题，无法对英文单词分割。还有你的方法，如果在文本文件太大的情况下会很占用内存，还有就是不知道TextView对前面不显示的文字做出什么样的处理，这可能是造成卡顿的原因。所以使用ListView可能是比较好的选择

**Comment by newbiechen1024** [comment]
噗，之前我觉得太容易点到了，把它缩小了。。。如果你想改的话，在PageView.onTouchEvent()中的这行
```java
 case MotionEvent.ACTION_UP:
                if (moveX == 0 && moveY == 0){
                    //是否点击了中间 (我是在这里判定是否唤起菜单的，你可以自己先改一下)
                    if (x > mViewWidth / 4 && x < mViewWidth * 3 / 4    
                            && y > mViewHeight / 3 && y < mViewHeight * 2 / 3) {
                        if (mTouchListener != null) {
                            mTouchListener.center();
                        }
                        return true;
                    }
```

**Comment by newbiechen1024** [comment]
卡顿真的很明显啊。。我只在虚拟机上测试没在真机上测过，做完就提交了。(说出来别打我~~)
上下滑动还有一堆问题，我最近尽量把卡顿的问题解决了orz~。

**Comment by funwell** [comment]
上下滑动确实好卡。目前有木有优化思路或者优化计划？

**Comment by newbiechen1024** [comment]
拖了好久了，不过实在没有空更新(；′⌒`)。有能力的小伙伴，希望能帮忙改一下，练练手。我觉的修复应该不难，逻辑挺简单的。造成卡顿的原因就两种，一种逻辑一种绘制。但是我逻辑写的简单，不可能造成卡顿(虽然没测试过)，所以就觉得可能是绘制流程过于复杂的问题，那就需要简化绘制流程。
