### ISSUE TITLE
全面屏手机退出全屏布局会上移，这个怎么解决，体验不太好

### ISSUE THREAD

**Issue by MrBoudar** [newbiechen1024/NovelReader#56]
建议作者优化下,谢谢

**Comment by circularity** [comment]
清单文件加入这个属性
<meta-data android:name="android.notch_support" android:value="true"/>

**Comment by MrBoudar** [comment]
> 清单文件加入这个属性

什么属性，屏占比吗，不行的

**Comment by MrBoudar** [comment]
> meta-data android:name="android.notch_support" android:value="true"
> 清单文件加入这个属性

这个属性也不行的，你可以试下
