### ISSUE TITLE
怎么监听翻页动画已经完成呢?

### ISSUE THREAD

**Issue by fcscr126608** [newbiechen1024/NovelReader#57]
如题，版主能解答一下吗，想翻页动画（主要是横向翻页时）完成之后处理一些事情，请问可以实现么

**Comment by le9527** [comment]
提供下我写的：在PageView的TouchListener里面添加一个你需要处理的事件的方法，在onTouchEvent()里面的ACTION_UP里面的mPageAnim.onTouchEvent(event);执行之前调用你添加的方法
