### ISSUE TITLE
我的手机每次在阅读界面都很难点击到中间的那个区域唤起菜单。

### ISSUE THREAD

**Issue by cc976655** [newbiechen1024/NovelReader#6]

**Comment by cc976655** [comment]
我也是在如风的那个基础上来改这个，但是效果都不理想，楼主这个做的很好，star一个！

**Comment by newbiechen1024** [comment]
噗，之前我觉得太容易点到了，把它缩小了，可能是有点小了，我改一下。。。如果你想改的话，在PageView.onTouchEvent()中的这行。(我也复制过来 0 0)

 case MotionEvent.ACTION_UP:
                if (moveX == 0 && moveY == 0){
                    //是否点击了中间 (我是在这里判定是否唤起菜单的，你可以自己先改一下)
                    if (x > mViewWidth / 4 && x < mViewWidth * 3 / 4    
                            && y > mViewHeight / 3 && y < mViewHeight * 2 / 3) {
                        if (mTouchListener != null) {
                            mTouchListener.center();
                        }
                        return true;
                    }

**Comment by cc976655** [comment]
不是中间区域太小的问题，我自己重新写了一下计算X，Y偏移量的代码，解决这个问题：
private int DownX = 0;
    private int DownY = 0;
    @Override
    public boolean onTouchEvent(MotionEvent event) {
        super.onTouchEvent(event);
        if (!canTouch && event.getAction() != MotionEvent.ACTION_DOWN) return true;
        int x = (int) event.getX();
        int y = (int) event.getY();
        switch (event.getAction()){
            case MotionEvent.ACTION_DOWN:
                DownX = (int) event.getX();
                DownY = (int) event.getY();
                canTouch = mTouchListener.onTouch();
                mPageAnim.onTouchEvent(event);
                break;
            case MotionEvent.ACTION_MOVE:
                moveX = (int) event.getX() - DownX;
                moveY = (int) event.getY() - DownY;
                mPageAnim.onTouchEvent(event);
                break;
            case MotionEvent.ACTION_UP:
                if (moveX == 0 && moveY == 0){
                    //是否点击了中间
                    if (x > mViewWidth / 4 && x < mViewWidth * 3 / 4
                            && y > mViewHeight / 3 && y < mViewHeight * 2 / 3) {
                        if (mTouchListener != null) {
                            mTouchListener.center();
                        }
                        return true;
                    }
                }
                mPageAnim.onTouchEvent(event);
                break;
            default:
                mPageAnim.onTouchEvent(event);
                break;
        }
        return true;
    }
不知道是不是原先代码有问题，2333333~

**Comment by funwell** [comment]
点击中间区域根本不能呼起菜单。。

**Comment by newbiechen1024** [comment]
请问是在哪台手机上面。。呼出菜单的原理是:判断当前的点击行为是点击还是滑动，如果是点击行为，再判断其是否点击到了屏幕指定的区域。代码注释在下面:
```java
 @Override
    public boolean onTouchEvent(MotionEvent event) {
        super.onTouchEvent(event);
        if (!canTouch && event.getAction() != MotionEvent.ACTION_DOWN) return true;

        int x = (int) event.getX();
        int y = (int) event.getY();
        switch (event.getAction()){
            case MotionEvent.ACTION_DOWN:
               //1. 按下时候将 moveX 和 moveY 设置为0。
                moveX = 0;
                moveY = 0;
                canTouch = mTouchListener.onTouch();
                mPageAnim.onTouchEvent(event);
                break;
            case MotionEvent.ACTION_MOVE:
                moveX = x;
                moveY = y;
                mPageAnim.onTouchEvent(event);
                break;
            case MotionEvent.ACTION_UP:

                //2. 当按起的时候如果没有进行过拖拽，那么 moveX 和 moveY 的值就是 0 
                //进入唤起菜单的逻辑
                if (moveX == 0 && moveY == 0){

                    //设置中间区域范围
                    if (mCenterRect == null){
                        mCenterRect = new RectF(mViewWidth/5,mViewHeight/3,
                                mViewWidth*4/5,mViewHeight*2/3);
                    }

                    //3. 这个时候再判断是否点击的中间区域
                    if (mCenterRect.contains(x,y)) {
                        if (mTouchListener != null) {
                            mTouchListener.center();
                        }
                        return true;
                    }
                }
                mPageAnim.onTouchEvent(event);
                break;
            default:
                mPageAnim.onTouchEvent(event);
                break;
        }
        return true;
    }
```
之前有朋友说，在不同的手机上 moveX 和 moveY 的值在 ACTION_UP 存在不为0的问题，希望能够测一测是不是这个问题。如果是这个问题，我希望能够获取到具体的数值，进行相应的改进，谢谢。

**Comment by funwell** [comment]
我是用galaxy s5测试的。我断点试下看看具体是什么值。

**Comment by cc976655** [comment]
我在我一加5，魅蓝NOTE5，红米4X上都用你的代码测试过了，点击中间区域无法唤起菜单。

**Comment by newbiechen1024** [comment]
好的，我一直用的是虚拟机，所以没有发现这个问题。。我去找找原因。

**Comment by newbiechen1024** [comment]
我暂时修复了一下，由于我没有测试机型，所以不知道修改是否成功。我觉得可能发生这个问题的原因是，某些机型点击时候会发生 ACTION_MOVE 事件，并进行小距离的滑动。最后导致 ACTION_UP 的时候 moveX 和 moveY 不为 0 的原因造成了。我增加了 TOUCH_SLOP 判断，不知道能不能修复这个问题。

**Comment by funwell** [comment]
就是滑动距离的问题。这个问题在onTouchEvent处理时很经常遇到，用模拟器是感受不了的，得真机测试才能发现。
目前该问题已修复。
