### ISSUE TITLE
AS打开项目时出错

### ISSUE THREAD

**Issue by cnvipstar** [newbiechen1024/NovelReader#9]
2017/9/14
上午6:22	Gradle sync started

上午6:22	Invalid VCS root mapping
				The directory /Users/sun/Downloads/android/NovelReader-master is registered as a Git root, but no Git repositories were found there.
				Configure

上午6:22	Gradle sync failed: Connection refused
				Consult IDE log for more details (Help | Show Log)

新手小白，请帮忙解答一下，非常感谢！

**Comment by newbiechen1024** [comment]
这是配置问题，遇到这种问题可以用 google 搜索一下。我搜索到的解决方法是
![](http://img.blog.csdn.net/20160512154307809)
选中红色错误地方，点击减号。不知道对你有没有帮助。

如果还没有解决，也可能是我在 gradle.properties 中添加了代理，下面这行:
```
systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=1080
systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=1080
```
可能删除一下就好了

**Comment by LeeTech** [comment]
记得把代理去掉，不然依赖包的下载代理地址都会指向这个地址

**Comment by tianshaokai** [comment]
依赖包无法下载

**Comment by tianshaokai** [comment]
删除了代理终于下载下来了
